### ISSUE TITLE
Program Change Null-State Requested

### ISSUE THREAD

**Issue by tripngroove** [kilpatrickaudio/CARBON#10]
Tracks are initialized with Program Change information set to 0 (null/unset?), but once this parameter has been changed it is impossible to again set it to 0. The only method I found to remove it was to load an entirely blank song.

This creates a problem with any equipment that doesn't have the ability to filter out incoming program change messages.

**Comment by kilpatrickaudio** [comment]
This is on the todo list as requested by another user. We plan to do it as part of the next release.

The meantime, if you don't set a program on a track it won't send one... there's just currently no way to reset it.
