### ISSUE TITLE
Random / different motion types

### ISSUE THREAD

**Issue by kilpatrickaudio** [kilpatrickaudio/CARBON#23]
A user requested random / different motion types similar to how the K4815 Pattern Generator works. This seems like a good idea.

**Comment by tomoe97** [comment]
I strongly support this request for different direction modes and motion types, such as random, ping pong, etc. I was really hoping Carbon could replace the K4815 Pattern Generator in my setup, but the Pattern Generator has additional motion types that are quite innovative, which are not replicated in Carbon. It would be great if some of the Pattern Generator's motion types could be ported over to Carbon.

**Comment by kilpatrickaudio** [comment]
This would require too much change to the underlying architecture and so I have decided to omit this.
