### ISSUE TITLE
More arpeggiator programs

### ISSUE THREAD

**Issue by kilpatrickaudio** [kilpatrickaudio/CARBON#28]
A user requested more arpeggiator programs. Submissions would be greatly appreciated.

**Comment by newsoner** [comment]
Yes, even for lower notes will be great

**Comment by DavidProuty** [comment]
The pattern I would really like to see is Note-Order. IE (plays back in the order notes have been pressed)

**Comment by kilpatrickaudio** [comment]
This is certainly possible. Thanks for the suggestion!

**Comment by DavidProuty** [comment]
Here is a link to an interesting one page read on arp behavior, just something to maybe help your inner muse.  http://lauterzeit.com/arp_lfo_seq_sync/

**Comment by kilpatrickaudio** [comment]
I will attempt to write some additional arp patterns in a future release.

**Comment by hamildad** [comment]
Took a look at Arpeggionome this morning.

In addition to the usual, they had:

Thumb up 1-2-1-3-1-4-1-5-1-6 etc.
Pinkie down 6-5-6-4-6-3-6-2-6-1 etc.
Diverge    3-4-2-5-1-6 or 4-3-5-2-6-1
Converge 6-1-5-2-4-3 or 1-6-2-5-3-4
Diverge&Converge 3-4-2-5-1-6-6-1-5-2-4-3
Converge&Diverge 1-6-2-5-3-4-4-3-5-2-6-1

hope this helps!

**Comment by kilpatrickaudio** [comment]
These are good suggestions, thank you.

**Comment by kilpatrickaudio** [comment]
Added more arps in 1.14.

- note order
- up/down with no repeat of top and bottom notes
- up, lowest note between each note
- down, highest note between each note
- repeat whatever is held down
