### ISSUE TITLE
Step size display not updated properly after scene change

### ISSUE THREAD

**Issue by IrwinKwan** [kilpatrickaudio/CARBON#35]
When you change scenes, the screen display for "Step" is not updated properly for the current track.

Reproducible on v1.02 as follows:
1. Load a song.
2. On Scene 1, confirm that the track is 1/16 step. Optionally, play it to confirm the step size.
3. On Scene 2, switch the track to another step size (ex: 1/8). Again, play it to confirm the step size.
4. Switch back to Scene 1. Observe that the step size does not update.

This applies only to the display: the sequencer does play back the step size at the correct step. When you switch off of the track and back to it, it also updates the display at this time.

**Comment by kilpatrickaudio** [comment]
Fixed.
