### ISSUE TITLE
Ability to record from seperate midi channels.

### ISSUE THREAD

**Issue by DavidProuty** [kilpatrickaudio/CARBON#36]
It would be great to have the ability to record from more then a single midi channel at once. For those of us that are doing key splits on separate channels or for the times when you need to capture two different midi channel streams at the same time. The way I picture it happening is if you selected track 1 & 2 so both led's are lit and those tracks are set to midi ch 1/2, the incoming note data on midi ch 1 & 2 would be recorded to their respective tracks. The way it is right now both tracks record note data from ch 1. so there is no way to capture two separate midi sources. .... unless I'm missing something?

**Comment by kilpatrickaudio** [comment]
This is a fairly advanced feature that is probably beyond the scope of CARBON. We'll leave it open for comments as for use cases for now, but I don't see this as a super useful feature since most people won't have the facility to generate two MIDI channels of input at once.
