### ISSUE TITLE
Would be possible to set a range for MAGIC?

### ISSUE THREAD

**Issue by Roisner** [kilpatrickaudio/CARBON#46]
For example to be able to choose to MAGIC from C2 to C4 only(per track).

**Comment by kilpatrickaudio** [comment]
Okay, I'll look into that.

**Comment by Roisner** [comment]
With this Carbon would be the best SEQ ;)

**Comment by hamildad** [comment]
this would be good as I don't use Magic much as the results are too unexpected to be useful in a live setting.

**Comment by lineofcontrol** [comment]
I must admit. I never use magic esp love as it is too random. I would love for it to be a fill that works whole held down and then when you let go it reverts to your original pattern.

**Comment by kilpatrickaudio** [comment]
This is being handled in #85 so I'm going to close this and focus on that one as it explains how it will be implemented.
