### ISSUE TITLE
8x10 font missing from repository

### ISSUE THREAD

**Issue by IrwinKwan** [kilpatrickaudio/CARBON#50]
The 8x10 font is missing from the repository:

    make: *** No rule to make target `src/text/font_smalltext_8x10.c', needed by `build/font_smalltext_8x10.c.o'.  Stop.

    ./src/gfx.c:181: undefined reference to `font_smalltext_8x10_bitmap'

**Comment by kilpatrickaudio** [comment]
Wasn't being tracked in Git. Now fixed.
