### ISSUE TITLE
Additional sequence transformations

### ISSUE THREAD

**Issue by Jumbuktu** [kilpatrickaudio/CARBON#52]
Currently there is a button for retrograde sequence transformations (direction). It would be good to have some of the other possible transformations, such as inversion, augmentation and diminishment. Rather than using multiple key combos, the direction button could call up a menu (with direction as the default) listing all the possibilities, so the user could select which one to apply. It would mean changing direction would take 2 button presses instead of 1, but this would be a small price to pay for the additional functionality.

**Comment by kilpatrickaudio** [comment]
Due to time constrainst and to maintain product consistency we have decided to focus mainly on bug reports. Please consider forking the code if you wish to add major features such as this. Quality pull requests may be considered for the official release versions
