### ISSUE TITLE
Microtonal scales

### ISSUE THREAD

**Issue by Jumbuktu** [kilpatrickaudio/CARBON#53]
Posting this after an email discussion with Andrew.

Whilst I would not place this one at the top of my priority list, it seems like it would be relatively easy to add some micro-tonal scales to the tonality scale selection menu.  Given that there are not that many CV / gate sequencers with built-in micro-tonal quantisation, this would be a unique feature for those wanting to explore the realms of alternative tuning.

In my last email from Andrew, he noted that this might be feasible for the CV outputs, but not for MIDI, since the pitches are defined by MIDI note number.  However, I have heard of MIDI gear that can handle alterations to the MIDI notes simply by sending a pitch-bend message along with the note number, so I think it would be feasible to cover all outputs.

I think it would be relatively easy to handle scales which retain the same octave structure as the Western 12-tone equal temperament scale, such as Just tuning or some of the alternative well-tempered scales.  It should also be straightforward to incorporate some non-Western scales, such as some African, Indian or Gamelan scales.  These could be implemented as adjustments to the default Western scale.

Where things get difficult is in dealing with scales with different 'octave' sizes (e.g. the alpha and gamma scales invented by Wendy Carlos), or different numbers of sub-divisions within the octave (e.g. quarter tone scales).  The problem here is getting the MIDI note numbers and a standard keyboard to map onto the resulting notes, which are generally going to number more or fewer than 12 to the octave.  Some of these could probably be done (CV only) by using a combination of an adjusted scale and the octave scaling parameter that is already in Carbon.  However, I am not sure how easy it would be to make sense of this within the sequencer displays.

Whilst I would dearly love to have the Carlos scales available on Carbon, I would settle for just the first group of scales mentioned above (conventional octaves) as an enhancement that would not require extensive rework.

Any other users care to comment?

**Comment by kilpatrickaudio** [comment]
Due to time constrainst and to maintain product consistency we have decided to focus mainly on bug reports. Please consider forking the code if you wish to add major features such as this. Quality pull requests may be considered for the official release versions
