### ISSUE TITLE
added CV/gate pair functionality

### ISSUE THREAD

**Issue by hamildad** [kilpatrickaudio/CARBON#56]
There is currently no way to assign Note, Velo & CCs to a single track in Carbon.

AAAA mode seems to work for note only and ABCD cannot be used as you can only set two outputs on a track. ( so A&B only)

I would like track one to transmit note,velocity & 2x CC messages to CV/gate pair 1-4.
I currently use track one and track two, ( track one A-Note B velocity; track two CC1, CC74) and press live on both tracks, but this means I only have 4 other tracks to use as is not a great workflow.

this will allow live playing on track one using a synth connected to the 4 pairs, whist the other tracks use DIN and USB midi.

this functionality should be also available in interface mode.

**Comment by kilpatrickaudio** [comment]
This seems like a special use case and sort of breaks the current layout of how we designed the CV/gate pairing modes. Personally I would probably dedicate a second track for the CCs as these are not really related to the notes at all. I'm going to close this for now as this seems a bit too complicated for the current scope of what CARBON is offering.
