### ISSUE TITLE
Midi- Export

### ISSUE THREAD

**Issue by immerfroehlich** [kilpatrickaudio/CARBON#6]
Hi,

it would be really nice if the Carbon would be able to export
the recorded MIDI notes/commands to a MIDI file. So you
would be able to use your material on your DAW for example.

Could you please consider implementing this feature?

Kind regards,
immerfroehlich

**Comment by kilpatrickaudio** [comment]
Yes we have been looking at  implementing a computer software to do this. 

Cheers,

Andrew

**Comment by DavidProuty** [comment]
Also it would be nice to do the opposite and import small midi loops into Carbon.

**Comment by CheckMate808** [comment]
I'd also be happy with exporting and importing MIDI notes. d;o)

**Comment by kilpatrickaudio** [comment]
This would require a custom app which I do not have the resources to write.
