### ISSUE TITLE
Possible to create a count-in or preroll to the record function?

### ISSUE THREAD

**Issue by flopass** [kilpatrickaudio/CARBON#64]
It's very useful on my Analog Keys to load a bar or two of preroll so I can ready myself for recording to the sequencer. Is it possible to add this as an option for Carbon?

**Comment by kilpatrickaudio** [comment]
Duplicate of issue #20 which is scheduled to be worked on.

**Comment by flopass** [comment]
I know this has merged with issue #20, but is there any progress with this possible feature implementation?

**Comment by kilpatrickaudio** [comment]
We will try to have time for another release this fall and will likely tackle the lead-in request at this time.
