### ISSUE TITLE
Direction not reflected on GUI when changing Scenes

### ISSUE THREAD

**Issue by hamildad** [kilpatrickaudio/CARBON#71]
Carbon 1.8 firmware.

When changing scenes within a Song, a sequence change of direction is not reflected in the GUI or in the DIR indicator.

So you can get scenes which say FWD on the screen but have the sequence going backwards. This happens when different Scenes within a song all have different directions and you are using SCENE+Number to switch between them.

**Comment by kilpatrickaudio** [comment]
Fixed! Will be in next binary release. (1.09 or later)
