### ISSUE TITLE
Scale Quantizing does not work

### ISSUE THREAD

**Issue by jramonas** [kilpatrickaudio/CARBON#76]
I can select a certain scale through 'tonality settings', but it does not have any affect on note options when I then try to edit a step - i.e. if I were to select "harmonic minor" notes available are not within the scale. Is there a firmware update I should be downloading? John

**Comment by kilpatrickaudio** [comment]
The TONALITY setting is an output filter mode and does not affect the underlying notes. This allows any notes to be editing / recorded and the tonality changed without changing the actual notes.
