### ISSUE TITLE
Scene 6 doesn't save track mutes

### ISSUE THREAD

**Issue by overthereinabox** [kilpatrickaudio/CARBON#77]
I've got some muted tracks in scene 6. Every time I load the song though, all tracks are unmuted. This only occurs in scene 6, all other scenes function correctly. I can mute the tracks manually and save the song again, but every time I load the song, the same thing happens. Problem persists post v1.10 fw upload.

Roy.

**Comment by kilpatrickaudio** [comment]
Fixed in 1.11.

**Comment by overthereinabox** [comment]
thanks for the quick turnaround, v1.11 has done the trick. Roy.
