### ISSUE TITLE
Song chaining - is it possible?

### ISSUE THREAD

**Issue by overthereinabox** [kilpatrickaudio/CARBON#78]
Andrew, would you consider an enhancement to allow song chaining??

**Comment by kilpatrickaudio** [comment]
This is not likely practical without a major design change to how songs are loaded and stored. Currently there can only be one song loaded at once, and currently this is not dynamically allocated so it's not easy to preload a new song and then swap to it on the fly. I see the use case this but believe it is beyond the scope of this product.
