### ISSUE TITLE
Request of MIDI Global Channel 

### ISSUE THREAD

**Issue by Oehi** [kilpatrickaudio/CARBON#79]
Hi all,
i like to request a global MIDI channel to transpose all voice tracks with one MIDI note. The option to use channel 10 with the selected tracks seems to be a difficult because you always have to select all tracks. The other option with the bias track leads to the effect to use one of the six tracks just for transposing which makes the sequencer a 5 track device.
Thanx in advance,
Werner

**Comment by kilpatrickaudio** [comment]
This is already possible. Note events in remote control modes affect all tracks: http://www.kilpatrickaudio.com/?p=carbon-manual#note_control
