### ISSUE TITLE
cv not working

### ISSUE THREAD

**Issue by boerup** [kilpatrickaudio/CARBON#81]
I am unable to get any cv out. Everything looks correct in the settings, but nothing is coming out. 
Any thoughts about what I might be doing wrong?

Br, B

**Comment by kilpatrickaudio** [comment]
This is not a bug. Please request tech support by email: andrew@kilpatrickaudio.com

As a quick tip, please see the manual section about the CV outputs here: http://www.kilpatrickaudio.com/?p=carbon-manual#cvgate

All questions we get about CV outputs turn out to be incorrect settings.
