### ISSUE TITLE
Record into a repeated loop

### ISSUE THREAD

**Issue by Jumbuktu** [kilpatrickaudio/CARBON#82]
I find it frustrating that you only get one time through a loop to record in real-time recording mode.  Particularly for drum loops, I would like to be able to keep adding notes  each time through the loop, until I turn recording off.  That's how it works on most drum sequencers that have real-time record.

Personally, I would like this to be the default way of using real-time record, but I could live with an option to switch between one-loop recording and unlimited looping.

**Comment by kilpatrickaudio** [comment]
I've reopened issue #9 which is basically this plus a few other things. I'll try to get it figured out for the next major release. Closing this now.
