### ISSUE TITLE
Clock Reset Alternates

### ISSUE THREAD

**Issue by MDTF** [kilpatrickaudio/CARBON#86]
If the "Clock out" and "Reset Out" are connected to a drum machine (in my case the Tanzbaer), and one starts the sequencer, the drum machine will be slaved to the clock just fine. However, when doing a reset on the Carbon (or stop-reset-start), the drum machine will not play. After another reset it follows the Carbon again.

(I'm not sure whether this is a bug or just some feature that I missed. Of course, the problem could also be my drum machine? It's set to listen to impuls rather than level, so that should be ok.)

**Comment by kilpatrickaudio** [comment]
The reset pulse is tied to the start command. The reset pulse should occur just before the first clock pulse, so perhaps it's a problem with how your drum machine is interpreting the clock signals. I'm going to close this for now since I don't think it's a bug.
