### ISSUE TITLE
MIDI output 2 not working

### ISSUE THREAD

**Issue by boerup** [kilpatrickaudio/CARBON#88]
Hello

I have MIDI output 1 & 2 set to absolutely the same settings. However, there is only MIDI activity from output 1. Nothing from output 2. Same cable, same target device. Am I missing something, or is output 2 simply not working? 

![carbon-midi-problems](https://user-images.githubusercontent.com/25017099/36545842-2469ae5a-17ea-11e8-81e3-887c67d1df1d.png)

**Comment by kilpatrickaudio** [comment]
Both outputs A and B appear to be set to MIDI DIN1 on the Out Port A and Out Port B screens. Try setting one of them to MIDI DIN2 instead.

**Comment by kilpatrickaudio** [comment]
I'm going to assume it was not actually an issue so this is closed.
