### ISSUE TITLE
More scenes (second try)

### ISSUE THREAD

**Issue by Jumbuktu** [kilpatrickaudio/CARBON#90]
I know Andrew has rejected this before, but I would like to raise it again.  After using Carbon for more than 12 months, I now more than ever feel that this is the most important enhancement of them all.  I love everything else that is being rolled out, and it's great to see that development of Carbon has not been abandoned.

The case in favour:  Carbon is a great live sequencer, but there are so many important parameters (track mute, direction, transpose, start step, step length etc) that it is difficult to change them all at once, even using MIDI control.  Scenes become the way to experiment with sections and change things on the fly.

My guess is that adding more scenes is not difficult in the code, the only tricky issue being how to use the buttons to create a logical interface.  I would be satisfied with just 6 more Scenes, accessed using the Shift button together with the Scene button.  Shift is counter-intuitive fro copying anyway, so i would be happy to move Scene copy to some other key combination - perhaps Scene plus the Load (Save) button, as this button makes sense in the context of copying ('saving').

Hopefully Andrew can reconsider this enhancement for the next firmware upadte.

**Comment by kilpatrickaudio** [comment]
I've taken note of this and agree that it would be good to do. I've reopened the old issue #59 and will close this so all discussion remains there.

**Comment by Jumbuktu** [comment]
Great, thanks Andrew! Happy to wait for the next release - I am keen to get 
the current release with all the new goodies you have been working on.

BillB
